# Generated by Django 3.2 on 2022-01-15 21:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(default=api.models.hex_uuid, max_length=32)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
